### ISSUE TITLE
Depreciated modules

### ISSUE THREAD

**Issue by wabi88** [thirdweb-example/community-rewards#2]
There's a few depreciated modules specifically unstable_getServerSession and getNFTCollection. I changed to getServerSession and getContract. I've added my .env.local and added my Client ID, Client Secret and private key but instead of < > I used " " because I was receiving an error. 
I've changed the NFT Collection address to my own on the generate-signature.js and the index.js and added my Discord Server ID to the check-is-in-server.js and generate-signature.js.

Now, I receive a decryption operation failed error and data?.find is not a function error from the check-is-in-server.js.

Not sure if I'm doing something wrong, I followed the readme 3 different times and for a beginner I'm normally pretty good at figuring stuff out but I think this might be an error in the code somewhere.

When I run dev it just gets stuck on Checking... 

When I run my console on chrome it states "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

**Comment by avneesh0612** [comment]
the template has been updated now
